export const bands = [
  {
    name: "Echo",
    bio: "Echo is a dream-pop band known for their ethereal soundscapes and haunting melodies. Formed in 2015, they have captivated audiences with their unique blend of electronic and acoustic elements.",
    genre: ["Dream Pop"],
    foundedYear: 2015,
    country: "USA",
  },
  {
    name: "Mirage",
    bio: "Mirage is a synthwave band that brings the sounds of the 80s into the modern era. With their vibrant synth lines and catchy hooks, they create a nostalgic yet fresh auditory experience.",
    genre: ["Synthwave", "Electronic"],
    foundedYear: 2010,
    country: "UK",
  },
  {
    name: "Solar",
    bio: "Formed in 2012, Solar is a progressive rock band that explores the cosmic and the terrestrial through their expansive compositions and intricate musicianship.",
    genre: ["Progressive Rock"],
    foundedYear: 2012,
    country: "Canada",
  },
  {
    name: "Crimson",
    bio: "Crimson is a heavy metal band that has been shaking the underground scene since 2009. Known for their aggressive riffs and powerful vocals, they deliver an intense musical experience.",
    genre: ["Heavy Metal"],
    foundedYear: 2009,
    country: "Germany",
  },
  {
    name: "Velvet",
    bio: "Velvet blends alternative rock with post-punk influences to create a dark and brooding sound. Their melancholic lyrics and atmospheric instrumentals have garnered a dedicated following.",
    genre: ["Alternative Rock", "Post-Punk"],
    foundedYear: 2013,
    country: "Australia",
  },
  {
    name: "Midnight Mirage",
    bio: "Midnight Mirage is an indie rock band that captures the essence of late-night contemplation through their introspective lyrics and smooth guitar melodies.",
    genre: ["Indie Rock"],
    foundedYear: 2014,
    country: "USA",
  },
  {
    name: "Aurora",
    bio: "Aurora is a folk band that draws inspiration from nature and personal stories. Their harmonies and acoustic arrangements paint vivid pictures in the minds of their listeners.",
    genre: ["Folk"],
    foundedYear: 2011,
    country: "Norway",
  },
  {
    name: "Lunar Echoes",
    bio: "Lunar Echoes is an experimental band that pushes the boundaries of sound with their eclectic mix of genres and innovative use of technology in music production.",
    genre: ["Experimental", "Electronic"],
    foundedYear: 2016,
    country: "Japan",
  },
  {
    name: "Stellar",
    bio: "Stellar is a post-rock band known for their expansive soundscapes and emotional crescendos. Their music takes listeners on a journey through the highs and lows of the human experience.",
    genre: ["Post-Rock"],
    foundedYear: 2008,
    country: "Sweden",
  },
  {
    name: "Phoenix",
    bio: "Phoenix is a pop-rock band with anthemic choruses and uplifting melodies. Since their formation in 2018, they have been spreading positivity and energy through their music.",
    genre: ["Pop Rock"],
    foundedYear: 2018,
    country: "France",
  },
  {
    name: "Nebula",
    bio: "Nebula is a space rock band that takes listeners on a cosmic journey with their expansive soundscapes and psychedelic influences.",
    genre: ["Space Rock"],
    foundedYear: 2011,
    country: "USA",
  },
  {
    name: "Zephyr",
    bio: "Zephyr is a progressive metal band known for their complex compositions and technical proficiency. They have been pushing the boundaries of metal since their formation.",
    genre: ["Progressive Metal"],
    foundedYear: 2010,
    country: "Germany",
  },
  {
    name: "Tempest",
    bio: "Tempest is a symphonic metal band that blends orchestral elements with heavy metal, creating a powerful and epic sound.",
    genre: ["Symphonic Metal"],
    foundedYear: 2014,
    country: "Netherlands",
  },
  {
    name: "Radiance",
    bio: "Radiance is an alternative rock band with anthemic choruses and dynamic arrangements, captivating audiences with their energetic performances.",
    genre: ["Alternative Rock"],
    foundedYear: 2009,
    country: "Australia",
  },
  {
    name: "Eclipse",
    bio: "Eclipse is a synth-pop band that combines catchy melodies with futuristic production, creating a sound that is both retro and contemporary.",
    genre: ["Synth-Pop"],
    foundedYear: 2012,
    country: "UK",
  },
  {
    name: "Cascade",
    bio: "Cascade is an indie folk band that draws inspiration from nature and personal experiences, creating music that is both intimate and expansive.",
    genre: ["Indie Folk"],
    foundedYear: 2015,
    country: "Canada",
  },
  {
    name: "Voyager",
    bio: "Voyager is a progressive rock band that explores complex themes and intricate musical landscapes, taking listeners on a journey through sound.",
    genre: ["Progressive Rock"],
    foundedYear: 2007,
    country: "USA",
  },
  {
    name: "Zenith",
    bio: "Zenith is a post-metal band known for their atmospheric sound and dynamic compositions, blending heavy riffs with melodic passages.",
    genre: ["Post-Metal"],
    foundedYear: 2013,
    country: "Finland",
  },
  {
    name: "Harmony",
    bio: "Harmony is a folk rock band that combines traditional folk instruments with modern rock elements, creating a sound that is both nostalgic and innovative.",
    genre: ["Folk Rock"],
    foundedYear: 2010,
    country: "Ireland",
  },
  {
    name: "Reverie",
    bio: "Reverie is a dream pop band that crafts lush, immersive soundscapes with their ethereal vocals and atmospheric production.",
    genre: ["Dream Pop"],
    foundedYear: 2014,
    country: "France",
  },
];
